version: '3.9'

services:
  backend:
    build:
      context: ../../Backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    command: ["run", "start"]
